export const routes = {
  landing: "/",
  app: "/app",
  coleccion: "/app/coleccion",
  coleccionId: (id: string) => `/app/coleccion/${id}`,
  pieza: (id: string) => `/app/pieza/${id}`,
  buscar: "/app/buscar",
  guardados: "/app/guardados",
  compartir: "/app/coleccion/compartir",
  marcas: "/marcas",
  marcasElegir: "/marcas/elegir",
  marcasDashboard: "/marcas/dashboard",
  terminos: "/terminos",
  privacidad: "/privacidad",
} as const;
