export const routes = {
  landing: "/",
  app: "/app",
  coleccion: "/app/coleccion",
  coleccionId: (id: string) => `/app/coleccion/${id}`,
  pieza: (id: string) => `/app/pieza/${id}`,
  buscar: "/app/buscar",
  guardados: "/app/guardados",
  compartir: "/app/coleccion/compartir",
  compartirSku: (id: string) => `/app/coleccion/compartir?sku=${id}`,
  recient: "/recien",
  recientSku: (id: string) => `/recien?sku=${id}`,
  anoche: "/anoche",
  las21: "/las21",
  marca: (slug: string) => `/marca/${slug}`,
  marcas: "/marcas",
  marcasElegir: "/marcas/elegir",
  marcasOauth: "/marcas/oauth",
  marcasDashboard: "/marcas/dashboard",
  terminos: "/terminos",
  privacidad: "/privacidad",
  ayuda: "/ayuda",
  faq: "/faq",
  queEs: "/que-es",
  contacto: "/contacto",
} as const;
