import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const img = {
  tapado: "/images/tapado-coppola.jpg",
  saco: "/images/saco-frances.jpg",
  pantalon: "/images/pantalon-pinza.jpg",
  camisa: "/images/camisa-oxford.jpg",
  mocasin: "/images/mocasin-goma.jpg",
  tote: "/images/tote-lona.jpg",
  baguette: "/images/baguette-napa.jpg",
  bikini: "/images/bikini-triangulo.jpg",
  enteriza: "/images/enteriza-canale.jpg",
};

function sku({
  id,
  collection_id,
  brand,
  name,
  price_ars,
  talle,
  tela,
  corte,
  category,
  categoryLabel,
  chip,
  description,
  image = "",
}) {
  return {
    id,
    collection_id,
    brand,
    name,
    price_ars,
    talle,
    tela,
    corte,
    category,
    categoryLabel,
    chip,
    description,
    disclaimer: `Esta pieza vive en la tienda de ${brand}. Con pinta te lleva; ellos venden.`,
    store_url: `https://www.example.com/tienda/${id}`,
    image,
  };
}

const collections = [
  {
    id: "sastreria-de-agosto",
    number: "01",
    title: "Sastrería de agosto",
    subtitle: "Cinco piezas. Un look. Un lugar.",
    lede: "Cinco piezas de sastrería, juntas en su colección.",
    coverCta: "Ver las cinco piezas",
    coverImage: img.tapado,
    homeChip: "Sastrería",
    onTapa: true,
  },
  {
    id: "lo-que-lleva-el-look",
    number: "02",
    title: "Lo que lleva el look",
    subtitle: "Tote y baguette. El resto, en las manos.",
    lede: "Carteras en su propia colección.",
    coverCta: "Ver la colección",
    coverImage: img.tote,
    homeChip: "Carteras",
    onTapa: false,
  },
  {
    id: "un-solo-traje",
    number: "03",
    title: "Un solo traje",
    subtitle: "Bikini y enteriza. El verano, resuelto.",
    lede: "Trajes de baño, fuera de la sastrería.",
    coverCta: "Ver la colección",
    coverImage: img.bikini,
    homeChip: "Trajes de baño",
    onTapa: false,
  },
  {
    id: "vitrina",
    number: "00",
    title: "Vitrina",
    subtitle: "Todas las marcas. Un solo lugar.",
    lede: "Marcas de TiendaNube. Tocás, vas a su tienda.",
    coverCta: "Ver la vitrina",
    coverImage: "/images/tapa-sastreria.jpg",
    homeChip: "Todas",
    onTapa: false,
  },
];

const existing = [
  sku({
    id: "tapado-coppola",
    collection_id: "sastreria-de-agosto",
    brand: "Taller Recoleta",
    name: "Tapado Coppola",
    price_ars: 890000,
    talle: "M",
    tela: "Paño de lana",
    corte: "Oversize",
    category: "tapado",
    categoryLabel: "Tapado",
    chip: "sastreria",
    description:
      "Paño camel, hombro ancho. El tapado del look — y de la temporada.",
    image: img.tapado,
  }),
  sku({
    id: "saco-frances",
    collection_id: "sastreria-de-agosto",
    brand: "Sastrería del Bajo",
    name: "Saco Francés",
    price_ars: 440000,
    talle: "50",
    tela: "Sarga de lana",
    corte: "Sastrero",
    category: "saco",
    categoryLabel: "Saco",
    chip: "sastreria",
    description:
      "Cuadros windowpane, hombro suave. El saco que cierra el look de agosto.",
    image: img.saco,
  }),
  sku({
    id: "pantalon-pinza",
    collection_id: "sastreria-de-agosto",
    brand: "Paño Sur",
    name: "Pantalón Pinza",
    price_ars: 320000,
    talle: "48",
    tela: "Gabardina de algodón",
    corte: "Recto",
    category: "pantalon",
    categoryLabel: "Pantalón",
    chip: "sastreria",
    description:
      "Pinza marcada, caída recta. El pantalón del look, sin buscarlo en otra tienda.",
    image: img.pantalon,
  }),
  sku({
    id: "camisa-oxford",
    collection_id: "sastreria-de-agosto",
    brand: "Lino de Agosto",
    name: "Camisa Oxford",
    price_ars: 185000,
    talle: "M",
    tela: "Oxford de algodón",
    corte: "Regular",
    category: "camisa",
    categoryLabel: "Camisa",
    chip: "sastreria",
    description:
      "Rayas suaves, cuello italiano. La camisa que sostiene las cinco piezas.",
    image: img.camisa,
  }),
  sku({
    id: "mocasin-goma",
    collection_id: "sastreria-de-agosto",
    brand: "Horma Palermo",
    name: "Mocasín Goma",
    price_ars: 240000,
    talle: "42",
    tela: "Cuero vacuno",
    corte: "Clásico",
    category: "mocasin",
    categoryLabel: "Mocasín",
    chip: "calzado",
    description:
      "Suela de goma, capellada de cuero. El piso del look de agosto.",
    image: img.mocasin,
  }),
  sku({
    id: "tote-lona",
    collection_id: "lo-que-lleva-el-look",
    brand: "Atelier Costanera",
    name: "Tote Lona",
    price_ars: 160000,
    talle: "Único",
    tela: "Lona de algodón",
    corte: "Amplio",
    category: "tote",
    categoryLabel: "Tote",
    chip: "carteras",
    description:
      "Lona cruda, asas largas. Lo que lleva el look cuando las manos no alcanzan.",
    image: img.tote,
  }),
  sku({
    id: "baguette-napa",
    collection_id: "lo-que-lleva-el-look",
    brand: "Marroquinería San Telmo",
    name: "Baguette Napa",
    price_ars: 210000,
    talle: "Único",
    tela: "Napa de ternera",
    corte: "Compacto",
    category: "baguette",
    categoryLabel: "Baguette",
    chip: "carteras",
    description:
      "Napa suave, solapa chica. La baguette del look, en su propia colección.",
    image: img.baguette,
  }),
  sku({
    id: "bikini-triangulo",
    collection_id: "un-solo-traje",
    brand: "Mar del Este",
    name: "Bikini Triángulo",
    price_ars: 98000,
    talle: "S",
    tela: "Lycra mate",
    corte: "Triángulo",
    category: "bikini",
    categoryLabel: "Bikini",
    chip: "trajes-de-bano",
    description:
      "Triángulo clásico, lazo en la nuca. Un traje, dos piezas, una colección.",
    image: img.bikini,
  }),
  sku({
    id: "enteriza-canale",
    collection_id: "un-solo-traje",
    brand: "Línea Costera",
    name: "Enteriza Canalé",
    price_ars: 125000,
    talle: "M",
    tela: "Canalé de lycra",
    corte: "Enteriza",
    category: "enteriza",
    categoryLabel: "Enteriza",
    chip: "trajes-de-bano",
    description:
      "Canalé elástico, escote en U. La enteriza del único traje de la temporada.",
    image: img.enteriza,
  }),
];

const extras = [
  sku({
    id: "blazer-crudo",
    collection_id: "vitrina",
    brand: "Tela Norte",
    name: "Blazer Crudo",
    price_ars: 285000,
    talle: "M",
    tela: "Lino pesado",
    corte: "Recto",
    category: "blazer",
    categoryLabel: "Blazer",
    chip: "ropa",
    description: "Crudo de lino, solapa estrecha. Un blazer de diario, de otra marca.",
    image: img.saco,
  }),
  sku({
    id: "vestido-liniers",
    collection_id: "vitrina",
    brand: "Costura Belgrano",
    name: "Vestido Liniers",
    price_ars: 198000,
    talle: "S",
    tela: "Algodón peinado",
    corte: "Midi",
    category: "vestido",
    categoryLabel: "Vestido",
    chip: "ropa",
    description: "Midi cruzado, manga corta. El vestido que no pide un look entero.",
    image: img.camisa,
  }),
  sku({
    id: "pollera-midi",
    collection_id: "vitrina",
    brand: "Atelier Núñez",
    name: "Pollera Midi",
    price_ars: 156000,
    talle: "38",
    tela: "Sarga de algodón",
    corte: "A-line",
    category: "pollera",
    categoryLabel: "Pollera",
    chip: "ropa",
    description: "Tabla suave, largo midi. Una pollera de otra vidriera.",
    image: img.pantalon,
  }),
  sku({
    id: "sweater-punto",
    collection_id: "vitrina",
    brand: "Prenda Cruda",
    name: "Sweater Punto",
    price_ars: 142000,
    talle: "M",
    tela: "Lana merino",
    corte: "Holgado",
    category: "sweater",
    categoryLabel: "Sweater",
    chip: "ropa",
    description: "Punto grueso, cuello redondo. Abrigo liviano de marca chica.",
    image: img.tapado,
  }),
  sku({
    id: "campera-gabardina",
    collection_id: "vitrina",
    brand: "Taller Caballito",
    name: "Campera Gabardina",
    price_ars: 268000,
    talle: "L",
    tela: "Gabardina",
    corte: "Recto",
    category: "campera",
    categoryLabel: "Campera",
    chip: "ropa",
    description: "Gabardina tostada, cierre oculto. La campera de otra tienda.",
    image: img.tapado,
  }),
  sku({
    id: "remera-hilo",
    collection_id: "vitrina",
    brand: "Lino Sur",
    name: "Remera Hilo",
    price_ars: 62000,
    talle: "M",
    tela: "Algodón peinado",
    corte: "Regular",
    category: "remera",
    categoryLabel: "Remera",
    chip: "ropa",
    description: "Hilo fino, cuello al ras. Una remera que no es de sastrería.",
    image: img.camisa,
  }),
  sku({
    id: "jumper-lana",
    collection_id: "vitrina",
    brand: "Corte Palermo",
    name: "Jumper Lana",
    price_ars: 175000,
    talle: "S",
    tela: "Lana y algodón",
    corte: "Recto",
    category: "jumper",
    categoryLabel: "Jumper",
    chip: "ropa",
    description: "Escote cuadrado, largo a la cadera. Otro taller, otra prenda.",
    image: img.saco,
  }),
  sku({
    id: "camisa-rayada",
    collection_id: "vitrina",
    brand: "Taller Villa Urquiza",
    name: "Camisa Rayada",
    price_ars: 118000,
    talle: "M",
    tela: "Popelin",
    corte: "Regular",
    category: "camisa",
    categoryLabel: "Camisa",
    chip: "ropa",
    description: "Rayas finas, puño simple. Camisa de barrio, no de colección.",
    image: img.camisa,
  }),
  sku({
    id: "buzo-entrenamiento",
    collection_id: "vitrina",
    brand: "Ritmo Palermo",
    name: "Buzo Entrenamiento",
    price_ars: 98000,
    talle: "L",
    tela: "Frisa de algodón",
    corte: "Holgado",
    category: "buzo",
    categoryLabel: "Buzo",
    chip: "deportiva",
    description: "Frisa suave, capucha chica. Para moverse, no para el look.",
    image: img.camisa,
  }),
  sku({
    id: "calza-pista",
    collection_id: "vitrina",
    brand: "Pista Norte",
    name: "Calza Pista",
    price_ars: 72000,
    talle: "M",
    tela: "Lycra reciclada",
    corte: "Largo",
    category: "calza",
    categoryLabel: "Calza",
    chip: "deportiva",
    description: "Cintura alta, tela mate. La calza de otra marca.",
    image: img.pantalon,
  }),
  sku({
    id: "top-salto",
    collection_id: "vitrina",
    brand: "Entrenar Sur",
    name: "Top Salto",
    price_ars: 54000,
    talle: "S",
    tela: "Lycra",
    corte: "Crop",
    category: "top",
    categoryLabel: "Top",
    chip: "deportiva",
    description: "Soporte medio, tiras finas. Un top de entrenamiento.",
    image: img.camisa,
  }),
  sku({
    id: "short-cancha",
    collection_id: "vitrina",
    brand: "Movida Costera",
    name: "Short Cancha",
    price_ars: 61000,
    talle: "M",
    tela: "Nylon liviano",
    corte: "Recto",
    category: "short",
    categoryLabel: "Short",
    chip: "deportiva",
    description: "Bolsillos laterales, secado rápido. Short de otra vidriera.",
    image: img.pantalon,
  }),
  sku({
    id: "campera-rompeviento",
    collection_id: "vitrina",
    brand: "Salto Urbano",
    name: "Campera Rompeviento",
    price_ars: 129000,
    talle: "M",
    tela: "Nylon ripstop",
    corte: "Holgado",
    category: "campera",
    categoryLabel: "Campera",
    chip: "deportiva",
    description: "Cierre corto, capucha plegable. Rompeviento de marca local.",
    image: img.tapado,
  }),
  sku({
    id: "remera-tecnica",
    collection_id: "vitrina",
    brand: "Cancha Abierta",
    name: "Remera Técnica",
    price_ars: 49000,
    talle: "L",
    tela: "Piqué técnico",
    corte: "Regular",
    category: "remera",
    categoryLabel: "Remera",
    chip: "deportiva",
    description: "Tela que respira, sisa amplia. Remera para la cancha.",
    image: img.camisa,
  }),
  sku({
    id: "bandolera-suela",
    collection_id: "lo-que-lleva-el-look",
    brand: "Cuero de Once",
    name: "Bandolera Suela",
    price_ars: 189000,
    talle: "Único",
    tela: "Cuero vacuno",
    corte: "Compacto",
    category: "bandolera",
    categoryLabel: "Bandolera",
    chip: "carteras",
    description: "Suela natural, tira ajustable. Otra cartera, otra marca.",
    image: img.baguette,
  }),
  sku({
    id: "clutch-noche",
    collection_id: "lo-que-lleva-el-look",
    brand: "Bolso del Centro",
    name: "Clutch Noche",
    price_ars: 134000,
    talle: "Único",
    tela: "Raso",
    corte: "Sobre",
    category: "clutch",
    categoryLabel: "Clutch",
    chip: "carteras",
    description: "Cierre escondido, asa de cadena. Para la noche, no para el look.",
    image: img.baguette,
  }),
  sku({
    id: "shopper-lona",
    collection_id: "lo-que-lleva-el-look",
    brand: "Napa Belgrano",
    name: "Shopper Lona",
    price_ars: 152000,
    talle: "Único",
    tela: "Lona pesada",
    corte: "Amplio",
    category: "shopper",
    categoryLabel: "Shopper",
    chip: "carteras",
    description: "Base ancha, asas cortas. El shopper de otra tienda.",
    image: img.tote,
  }),
  sku({
    id: "mini-bag",
    collection_id: "lo-que-lleva-el-look",
    brand: "Taller Almagro",
    name: "Mini Bag",
    price_ars: 168000,
    talle: "Único",
    tela: "Napa",
    corte: "Mini",
    category: "mini",
    categoryLabel: "Mini",
    chip: "carteras",
    description: "Cuerpo chico, solapa imán. Una mini de marca inventada.",
    image: img.baguette,
  }),
  sku({
    id: "cinto-cuero",
    collection_id: "vitrina",
    brand: "Cinto Sur",
    name: "Cinto Cuero",
    price_ars: 45000,
    talle: "85",
    tela: "Cuero vacuno",
    corte: "Fino",
    category: "cinto",
    categoryLabel: "Cinto",
    chip: "accesorios",
    description: "Hebilla quieta, tira de 2 cm. Un cinto, otra marca.",
    image: img.baguette,
  }),
  sku({
    id: "aros-aro",
    collection_id: "vitrina",
    brand: "Bijou Palermo",
    name: "Aros Aro",
    price_ars: 38000,
    talle: "Único",
    tela: "Metal bañado",
    corte: "Aro",
    category: "aros",
    categoryLabel: "Aros",
    chip: "accesorios",
    description: "Aro mediano, cierre oculto. Bijou de barrio.",
    image: img.tote,
  }),
  sku({
    id: "panuelo-seda",
    collection_id: "vitrina",
    brand: "Pañuelo Lino",
    name: "Pañuelo Seda",
    price_ars: 42000,
    talle: "Único",
    tela: "Seda",
    corte: "Cuadrado",
    category: "panuelo",
    categoryLabel: "Pañuelo",
    chip: "accesorios",
    description: "70 por 70, ruedo fino. Un pañuelo para el cuello o la cartera.",
    image: img.camisa,
  }),
  sku({
    id: "hebilla-plateada",
    collection_id: "vitrina",
    brand: "Hebilla Once",
    name: "Hebilla Plateada",
    price_ars: 29000,
    talle: "Único",
    tela: "Metal",
    corte: "Clásico",
    category: "hebilla",
    categoryLabel: "Hebilla",
    chip: "accesorios",
    description: "Plata mate, pasador simple. Un detalle, otra tienda.",
    image: img.mocasin,
  }),
  sku({
    id: "anteojos-sol",
    collection_id: "vitrina",
    brand: "Anteojos del Bajo",
    name: "Anteojos Sol",
    price_ars: 78000,
    talle: "Único",
    tela: "Acetato",
    corte: "Cuadrado",
    category: "anteojos",
    categoryLabel: "Anteojos",
    chip: "accesorios",
    description: "Acetato carey, lente gris. Anteojos de otra marca.",
    image: img.baguette,
  }),
  sku({
    id: "reloj-pulsera",
    collection_id: "vitrina",
    brand: "Reloj de Barrio",
    name: "Reloj Pulsera",
    price_ars: 96000,
    talle: "Único",
    tela: "Acero",
    corte: "Redondo",
    category: "reloj",
    categoryLabel: "Reloj",
    chip: "accesorios",
    description: "Caja chica, malla de acero. La hora, en otra vidriera.",
    image: img.mocasin,
  }),
  sku({
    id: "bikini-aro",
    collection_id: "un-solo-traje",
    brand: "Arena Chica",
    name: "Bikini Aro",
    price_ars: 89000,
    talle: "M",
    tela: "Lycra",
    corte: "Aro",
    category: "bikini",
    categoryLabel: "Bikini",
    chip: "trajes-de-bano",
    description: "Aro suave, tiras regulables. Otro traje, otra marca.",
    image: img.bikini,
  }),
  sku({
    id: "slip-costa",
    collection_id: "un-solo-traje",
    brand: "Costa Verde",
    name: "Slip Costa",
    price_ars: 54000,
    talle: "S",
    tela: "Lycra mate",
    corte: "Alto",
    category: "slip",
    categoryLabel: "Slip",
    chip: "trajes-de-bano",
    description: "Tiro alto, recorte lateral. La parte de abajo de otra tienda.",
    image: img.bikini,
  }),
  sku({
    id: "enteriza-nudo",
    collection_id: "un-solo-traje",
    brand: "Sal Pinamar",
    name: "Enteriza Nudo",
    price_ars: 118000,
    talle: "M",
    tela: "Lycra",
    corte: "Nudo",
    category: "enteriza",
    categoryLabel: "Enteriza",
    chip: "trajes-de-bano",
    description: "Nudo al frente, espalda abierta. Enteriza de la costa.",
    image: img.enteriza,
  }),
  sku({
    id: "pareo-ola",
    collection_id: "un-solo-traje",
    brand: "Ola Quietud",
    name: "Pareo Ola",
    price_ars: 46000,
    talle: "Único",
    tela: "Voile",
    corte: "Rectángulo",
    category: "pareo",
    categoryLabel: "Pareo",
    chip: "trajes-de-bano",
    description: "Voile liviano, ruedo crudo. El pareo que cierra el traje.",
    image: img.enteriza,
  }),
  sku({
    id: "saco-cruzado",
    collection_id: "vitrina",
    brand: "Sastre Villa Crespo",
    name: "Saco Cruzado",
    price_ars: 390000,
    talle: "50",
    tela: "Paño",
    corte: "Cruzado",
    category: "saco",
    categoryLabel: "Saco",
    chip: "sastreria",
    description: "Doble abotonadura, solapa ancha. Sastrería de otra casa.",
    image: img.saco,
  }),
  sku({
    id: "chaleco-sastre",
    collection_id: "vitrina",
    brand: "Paño Norte",
    name: "Chaleco Sastre",
    price_ars: 210000,
    talle: "48",
    tela: "Lana",
    corte: "Ajustado",
    category: "chaleco",
    categoryLabel: "Chaleco",
    chip: "sastreria",
    description: "Cinco botones, espalda de forro. Un chaleco, no el look de agosto.",
    image: img.saco,
  }),
  sku({
    id: "pantalon-vestir",
    collection_id: "vitrina",
    brand: "Corte Libertad",
    name: "Pantalón Vestir",
    price_ars: 245000,
    talle: "46",
    tela: "Lana fría",
    corte: "Recto",
    category: "pantalon",
    categoryLabel: "Pantalón",
    chip: "sastreria",
    description: "Pinza baja, basta sin dobladillo. Otro pantalón sastre.",
    image: img.pantalon,
  }),
  sku({
    id: "tapado-corto",
    collection_id: "vitrina",
    brand: "Taller Congreso",
    name: "Tapado Corto",
    price_ars: 520000,
    talle: "M",
    tela: "Paño",
    corte: "Corto",
    category: "tapado",
    categoryLabel: "Tapado",
    chip: "sastreria",
    description: "Largo a la cadera, hombro marcado. Tapado de otra sastrería.",
    image: img.tapado,
  }),
  sku({
    id: "bota-media",
    collection_id: "vitrina",
    brand: "Suela San Telmo",
    name: "Bota Media",
    price_ars: 198000,
    talle: "38",
    tela: "Cuero",
    corte: "Media caña",
    category: "bota",
    categoryLabel: "Bota",
    chip: "calzado",
    description: "Caña media, taco bajo. Bota de otra horma.",
    image: img.mocasin,
  }),
  sku({
    id: "zapatilla-lona",
    collection_id: "vitrina",
    brand: "Horma Norte",
    name: "Zapatilla Lona",
    price_ars: 112000,
    talle: "40",
    tela: "Lona",
    corte: "Baja",
    category: "zapatilla",
    categoryLabel: "Zapatilla",
    chip: "calzado",
    description: "Lona cruda, suela de goma. Zapatilla de marca local.",
    image: img.mocasin,
  }),
  sku({
    id: "sandalia-tira",
    collection_id: "vitrina",
    brand: "Paso Recoleta",
    name: "Sandalia Tira",
    price_ars: 89000,
    talle: "37",
    tela: "Cuero",
    corte: "Tira",
    category: "sandalia",
    categoryLabel: "Sandalia",
    chip: "calzado",
    description: "Tira ancha, cama plana. Sandalia de otra tienda.",
    image: img.mocasin,
  }),
  sku({
    id: "bota-cana",
    collection_id: "vitrina",
    brand: "Cuero y Goma",
    name: "Bota Caña",
    price_ars: 276000,
    talle: "39",
    tela: "Cuero engrasado",
    corte: "Caña alta",
    category: "bota",
    categoryLabel: "Bota",
    chip: "calzado",
    description: "Caña alta, suela track. Bota de invierno, otra marca.",
    image: img.mocasin,
  }),
  sku({
    id: "taco-bloque",
    collection_id: "vitrina",
    brand: "Taco Bajo",
    name: "Taco Bloque",
    price_ars: 154000,
    talle: "38",
    tela: "Cuero",
    corte: "Bloque",
    category: "taco",
    categoryLabel: "Taco",
    chip: "calzado",
    description: "Taco de 5 cm, puntera cuadrada. Un taco, no un mall.",
    image: img.mocasin,
  }),
  sku({
    id: "alpargata-yute",
    collection_id: "vitrina",
    brand: "Alpargata Sur",
    name: "Alpargata Yute",
    price_ars: 67000,
    talle: "41",
    tela: "Lona y yute",
    corte: "Clásico",
    category: "alpargata",
    categoryLabel: "Alpargata",
    chip: "calzado",
    description: "Yute natural, capellada de lona. Alpargata de barrio.",
    image: img.mocasin,
  }),
];

const more = [
  sku({
    id: "blazer-navy",
    collection_id: "vitrina",
    brand: "Corte Libertad",
    name: "Blazer Navy",
    price_ars: 310000,
    talle: "50",
    tela: "Lana fría",
    corte: "Recto",
    category: "blazer",
    categoryLabel: "Blazer",
    chip: "hombre",
    description: "Navy cerrado, solapa clásica. Sastrería de otra casa.",
    image: img.saco,
  }),
  sku({
    id: "jean-recto",
    collection_id: "vitrina",
    brand: "Tela Norte",
    name: "Jean Recto",
    price_ars: 145000,
    talle: "32",
    tela: "Denim",
    corte: "Recto",
    category: "jean",
    categoryLabel: "Jean",
    chip: "hombre",
    description: "Denim índigo, basta cruda. Un jean de otra vidriera.",
    image: img.pantalon,
  }),
  sku({
    id: "camisa-oxford-h",
    collection_id: "vitrina",
    brand: "Lino de Agosto",
    name: "Camisa Clara",
    price_ars: 129000,
    talle: "L",
    tela: "Oxford",
    corte: "Regular",
    category: "camisa",
    categoryLabel: "Camisa",
    chip: "hombre",
    description: "Oxford claro, cuello button-down. Camisa de barrio.",
    image: img.camisa,
  }),
  sku({
    id: "zapato-vestir",
    collection_id: "vitrina",
    brand: "Horma Palermo",
    name: "Zapato Vestir",
    price_ars: 220000,
    talle: "42",
    tela: "Cuero",
    corte: "Clásico",
    category: "zapato",
    categoryLabel: "Zapato",
    chip: "hombre",
    description: "Capellada lisa, suela de cuero. El piso de otra marca.",
    image: img.mocasin,
  }),
  sku({
    id: "anillo-sello",
    collection_id: "vitrina",
    brand: "Bijou Palermo",
    name: "Anillo Sello",
    price_ars: 52000,
    talle: "Único",
    tela: "Plata",
    corte: "Sello",
    category: "anillo",
    categoryLabel: "Anillo",
    chip: "joyas",
    description: "Plata mate, cara lisa. Un sello de otra casa.",
    image: img.baguette,
  }),
  sku({
    id: "collar-cadena",
    collection_id: "vitrina",
    brand: "Hebilla Once",
    name: "Collar Cadena",
    price_ars: 48000,
    talle: "Único",
    tela: "Acero",
    corte: "Fino",
    category: "collar",
    categoryLabel: "Collar",
    chip: "joyas",
    description: "Cadena fina, cierre langosta. Un collar, otra marca.",
    image: img.tote,
  }),
  sku({
    id: "pulsera-eslabon",
    collection_id: "vitrina",
    brand: "Reloj de Barrio",
    name: "Pulsera Eslabón",
    price_ars: 41000,
    talle: "Único",
    tela: "Acero",
    corte: "Eslabón",
    category: "pulsera",
    categoryLabel: "Pulsera",
    chip: "joyas",
    description: "Eslabón chato, cierre oculto. Pulsera de barrio.",
    image: img.mocasin,
  }),
  sku({
    id: "aros-perla",
    collection_id: "vitrina",
    brand: "Pañuelo Lino",
    name: "Aros Perla",
    price_ars: 36000,
    talle: "Único",
    tela: "Perla",
    corte: "Gota",
    category: "aros",
    categoryLabel: "Aros",
    chip: "joyas",
    description: "Perla chica, gancho fino. Aros de otra vidriera.",
    image: img.baguette,
  }),
  sku({
    id: "dije-plata",
    collection_id: "vitrina",
    brand: "Anteojos del Bajo",
    name: "Dije Plata",
    price_ars: 33000,
    talle: "Único",
    tela: "Plata",
    corte: "Chico",
    category: "dije",
    categoryLabel: "Dije",
    chip: "joyas",
    description: "Dije quieto, cadena aparte. Una joya, no un mall.",
    image: img.tote,
  }),
];

const SASTRERIA = new Set([
  "tapado-coppola",
  "saco-frances",
  "pantalon-pinza",
  "camisa-oxford",
  "saco-cruzado",
  "chaleco-sastre",
  "pantalon-vestir",
  "tapado-corto",
  "blazer-navy",
]);

const CALZADO = new Set([
  "mocasin-goma",
  "bota-media",
  "zapatilla-lona",
  "sandalia-tira",
  "bota-cana",
  "taco-bloque",
  "alpargata-yute",
  "zapato-vestir",
]);

const CARTERAS = new Set([
  "tote-lona",
  "baguette-napa",
  "bandolera-suela",
  "clutch-noche",
  "shopper-lona",
  "mini-bag",
]);

const TRAJES = new Set([
  "bikini-triangulo",
  "enteriza-canale",
  "bikini-aro",
  "slip-costa",
  "enteriza-nudo",
  "pareo-ola",
]);

const DEPORTIVA = new Set([
  "buzo-entrenamiento",
  "calza-pista",
  "top-salto",
  "short-cancha",
  "campera-rompeviento",
  "remera-tecnica",
]);

const ACCESORIOS = new Set([
  "cinto-cuero",
  "aros-aro",
  "panuelo-seda",
  "hebilla-plateada",
  "anteojos-sol",
  "reloj-pulsera",
  "anillo-sello",
  "collar-cadena",
  "pulsera-eslabon",
  "aros-perla",
  "dije-plata",
]);

function remapChip(item) {
  if (SASTRERIA.has(item.id) || item.chip === "sastreria") return "sastreria";
  if (CALZADO.has(item.id) || item.chip === "calzado") return "calzado";
  if (CARTERAS.has(item.id) || item.chip === "carteras") return "carteras";
  if (TRAJES.has(item.id) || item.chip === "trajes-de-bano") return "trajes-de-bano";
  if (DEPORTIVA.has(item.id) || item.chip === "deportiva") return "deportiva";
  if (ACCESORIOS.has(item.id) || item.chip === "accesorios") return "accesorios";
  return "ropa";
}

const skus = [...existing, ...extras, ...more].map((item, index) => ({
  ...item,
  chip: remapChip(item),
  published_at: 1_722_470_400_000 + index * 3_600_000,
}));

const catalog = {
  collections,
  skus,
};

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
writeFileSync(join(root, "data/seed.json"), `${JSON.stringify(catalog, null, 2)}\n`);
console.log(`wrote ${catalog.skus.length} skus`);
